development:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: "db/lab10_development.sqlite3"
  encoding: utf8

production:
  adapter: mysql2
  database: example_prod
  host: localhost
  username: root
  password: "123456"
  encoding: utf8
  reconnect: true

